### ISSUE TITLE
Merge consumer

### ISSUE THREAD

**Issue by domoritz** [uwescience/myria#348]
A consumer that merges ordered streams. 

It's probably a good idea to merge available data in the heap but only output when all connected producers have data available.

**Comment by senderista** [comment]
So how is this different from `edu.washington.escience.myria.operator.Merge`?

**Comment by domoritz** [comment]
Merge merges two inputs from different relations. A merge consumer would merge relations from multiple servers after a shuffle. In fact, I think we don't currently use the merge operator because we have no ordering guarantees when tuples come from multiple machines. We would have to add a sort but then we might as well just sort the union of two relations.

**Comment by senderista** [comment]
This should be superseded by https://github.com/uwescience/myria/issues/827
