### ISSUE TITLE
Unsecure Postgres Configuration 

### ISSUE THREAD

**Issue by stechu** [uwescience/myria#424]
Myria connects postgres via hostname:5401 (yes, hard coded port ).  See line 225 in [CatalogMaker.java](https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/coordinator/catalog/CatalogMaker.java#L225). 

This could be a security threat since it prevent us from disabling remote login for Postgres. 
@dhalperi : I guess that's the reason of the bot issue?

**Comment by dhalperi** [comment]
Believe this is fixed – postrgres machines have been updated to only allow login from CSE
