### ISSUE TITLE
RFC: Make GC setting configurable 

### ISSUE THREAD

**Issue by stechu** [uwescience/myria#437]
Following the discussion with @slxu today, I am reading this article 
(http://www.oracle.com/technetwork/java/javase/gc-tuning-6-140523.html).

I think it is useful to make the GC settings configurable and do some experiments to figure out which settings are best of default.

The settings that may worth to be configurable are:

1.  -Xmx, which we already do
2.  -Xms
3.  -XX:MaxGCPauseMillis=<N>
4.  -XX:GCTimeRatio
5.  the selection of garbage collection algorithm. e.g.
       XX:+UseParallelGC
6. etc.

**Comment by senderista** [comment]
Determining good default GC options is being tracked in https://github.com/uwescience/myria/issues/770
