### ISSUE TITLE
Sampling methods

### ISSUE THREAD

**Issue by domoritz** [uwescience/myria#501]
To run bootstrap, we would like to have native support for sampling.

* Random sampling without replacement
  * reservoir sampling
  * distributed: http://had00b.blogspot.com/2013/07/random-subset-in-mapreduce.html
* Random sampling with replacement
  * if size is known: http://ashenfad.blogspot.com/2011/06/single-pass-sampling-with-replacement.html
  * if size is unknown: http://www.researchgate.net/publication/220907271_Reservoir-Based_Random_Sampling_with_Replacement_from_Data_Stream/file/79e4150d095ba383d7.pdf

**Comment by domoritz** [comment]
@radion Feel free to take over this issue.

**Comment by radion** [comment]
I'm not entirely clear what is meant here by "running bootstrap". Also, what do we mean by native support for sampling?
I am currently working on adding a new operator that will do sampling without replacement in Myria.

**Comment by domoritz** [comment]
https://en.wikipedia.org/wiki/Bootstrapping_%28statistics%29 it will need sampling with replacement. In fact we need many samples with replacement in parallel. 

Native support just means that we have some efficient way in Myria.

**Comment by senderista** [comment]
Fixed in https://github.com/uwescience/myria/pull/749
