### ISSUE TITLE
Corrupt Data in HDFS?

### ISSUE THREAD

**Issue by jortiz16** [uwescience/myria#681]
Hi all, 

Not sure if this issue should be posted under myria-web or myria, but I'm currently having a data issue (this is more of a Stars cluster problem I think).

Before the break, I've been able to successfully load data from HDFS to the Myria Production cluster. A couple days ago I tried ingesting more data and got the following error: java.io.IOException: Could not obtain block: blk_4114039592741439689_1215467 

I googled this and found that it could possibly be that the data is corrupted. I ran  ``hadoop fsck /datasets/cosmo25p.768sg1bwK1C52`` and saw the following:

 Total size:	5734794030486 B
 Total dirs:	185
 Total files:	2074
 Total blocks (validated):	86803 (avg. block size 66066772 B)
  ********************************
  CORRUPT FILES:	1926
  MISSING BLOCKS:	66863
  MISSING SIZE:		4416271733577 B
  CORRUPT BLOCKS: 	66863
  ********************************

Many (if not all) the blocks seem to be corrupted or missing. What could have caused this?

Thanks!

**Comment by dhalperi** [comment]
This probably goes in *uwdb* somewhere. Maybe in Laurel's script repository?


----
Daniel Halperin
Director of Research for Scalable Data Analytics
eScience Institute
University of Washington

**Comment by dhalperi** [comment]
also, I fixed it. hint: did you check the hdfs cluster status? In
particular, whether the machines were up?

16 of the machines were down, so 16/18 of the blocks in the cluster were
missing. Even with 2x replication that's not going to help...


----
Daniel Halperin
Director of Research for Scalable Data Analytics
eScience Institute
University of Washington

On Sat, Jan 17, 2015 at 1:30 AM, Daniel Halperin <dhalperi@cs.washington.edu

**Comment by jortiz16** [comment]
Thanks! I had no idea I could check whether data nodes are alive. And next time I have a Stars-cluster related question, I'll make sure to issue it elsewhere.

**Comment by dhalperi** [comment]
http://hortonworks.com/kb/checking-the-health-of-hdfs-cluster/ , also
vega:50070 (I think, whatever the standard Hadoop ports are) from on campus.


----
Daniel Halperin
Director of Research for Scalable Data Analytics
eScience Institute
University of Washington
