### ISSUE TITLE
postgres hardcoded port

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria#684]
Two downsides:

1. postgres port is not the default port
2. when adding external databases, may be running on non-standard port.

User should be able to set the port in the JDBC connection string.

May end up involving #428

**Comment by BrandonHaynes** [comment]
I've worked around this on the Starcluster/EC2 side by replacing the constant in the source before compiling.  (Ugh.)

**Comment by dhalperi** [comment]
Fixed by #703
