### ISSUE TITLE
Sampling with/without Replacement

### ISSUE THREAD

**Issue by radion** [uwescience/myria#702]
* [x] Create a sample operator that takes as input a relation with a single tuple (n, k, b). Outputs list of tupleIDs.
* [x] Modify shuffle to not hash the attribute (shuffles based on raw value)
* [x] Master sample operator that outputs a relation (worker_id, n, k, b). Input is (worker_id, n)
* [ ] Modify Raco to generate query that is sequence of: write to temp table: `SELECT worker_id, count(*) GROUP BY worker_id`, temp table -> masterSample -> shuffle -> sample -> JOIN <- statefulApply tuple ids <- Relation R

**Comment by radion** [comment]
from conversation with @domoritz

**Comment by domoritz** [comment]
@radion Make sure that the algorithm we talked about is actually correct. I don't know whether there is guaranteed randomness when you only distribute the counts.

**Comment by radion** [comment]
See PR #735
