### ISSUE TITLE
Specify data partitioning during ingestion

### ISSUE THREAD

**Issue by jingjingwang** [uwescience/myria#715]
Currently a table is always round-robin partitioned, but we may want to specify a particular partitioning strategy when ingesting a table, e.g. hash-partition on some columns, or even having replications. There are several steps in my mind:
1) adding a partition function to JSON
2) adding the information of how a table is partitioned to catalog. We may need to know if a logical table has multiple physical tables that are partitioned in different ways to serve 3)
3) making the optimizer be aware of the information. 

I'll be pushing out 1) soon. A draft version of 2) seems to be not hard. 3) is a RACO issue.

**Comment by domoritz** [comment]
Will you be using shuffle without a hash function and just mod? Then we could just sue apply to achieve custom partitioning.

**Comment by dhalperi** [comment]
I think for the title of this issue, you need a subset of the lines of code in 3d406019576b505071ba77c67a756aa6a90b48e5 .

**Comment by dhalperi** [comment]
Except that, I think, that commit did it wrong. It shouldn't be `String partitionFunction`, it should be `PartitionFunction pf` -- we already can serialize and deserialize partition functions, after all!
