### ISSUE TITLE
cannot delete tables with derived views

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria#728]
@jortiz16 needs this

Attempting to overwrite a table with an view, e.g., `public:adhoc:snapshot1818Hash`, results in the following error:

```java
edu.washington.escience.myria.DbException: Query #69111.0 failed: ErrorCode: 0, SQLState: 2BP01, Msg: ERROR: cannot drop table "public:adhoc:snapshot1818Hash" because other objects depend on it
  Detail: view test depends on table "public:adhoc:snapshot1818Hash"
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
```

The program I used to attempt to do this was:

```myrial
a = empty(x:int);
store(a, public:adhoc:snapshot1818Hash);
```

**Comment by billhowe** [comment]
Ought to be a one word change:  DROP CASCADE

(But: if something goes wrong while dropping tables around the cluster,
won't we get into a bad state where some partitions are gone and others
aren't?  Ok by me to just ignore it for now, but if we want to fix it, we
can use TRUNCATE wrapped in a transaction, followed by drop.  This will be
slower, but not disastrously so in my experience.)

On Wed, Mar 25, 2015 at 11:31 AM, Daniel Halperin <notifications@github.com>
wrote:

> @jortiz16 <https://github.com/jortiz16> needs this
>
> Attempting to overwrite a table with an index, e.g.,
> public:adhoc:snapshot1818Hash, results in the following error:
>
> edu.washington.escience.myria.DbException: Query #69111.0 failed: ErrorCode: 0, SQLState: 2BP01, Msg: ERROR: cannot drop table "public:adhoc:snapshot1818Hash" because other objects depend on it
>   Detail: view test depends on table "public:adhoc:snapshot1818Hash"
>   Hint: Use DROP ... CASCADE to drop the dependent objects too.
>
> The program I used to attempt to do this was:
>
> a = empty(x:int);
> store(a, public:adhoc:snapshot1818Hash);
>
> This table is one of the few tables in the system that has an index on it,
> because @jortiz16 <https://github.com/jortiz16> created it manually –
> thus I suspect index as the issue. But it might be another derived
> structure that someone created manually of which I am not aware.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria/issues/728>.
>



-- 
Bill Howe
Associate Director and Senior Data Science Fellow, UW eScience Institute
Affiliate Faculty, Computer Science & Engineering
University of Washington
To acknowledge eScience: "Supported in part by the University of Washington
eScience Institute"

**Comment by dhalperi** [comment]
This is probably a false positive from a manual experiment.
