### ISSUE TITLE
What is the best way to mean-center an attribute?

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria#732]
I need to mean-center a bunch of tuples in Myria.  MyriaL doesn't support this inline (e.g., "`[from relation emit x - avg(x)]`"), and I understand why this isn't valid.  

So what is the best way to go about this?  Obviously I can take the cross product:

```
mean = [from relation emit avg(x) as _avg];
centered = [from relation, mean emit x - _avg];
```

Is there an alternate approach that is superior?  Or a way to convert a singleton relation back into a scalar that I am not aware of?

**Comment by billhowe** [comment]
On Tuesday, April 7, 2015, Brandon Haynes <notifications@github.com> wrote:

> I need to mean-center a bunch of tuples in Myria. MyriaL doesn't support
> this inline (e.g., "[from relation emit x - avg(x)]"), and I understand
> why this isn't valid.
>
> So what is the best way to go about this? Obviously I can take the cross
> product:
>
> mean = [from relation emit avg(x) as _avg];
> centered = [from relation, mean emit x - _avg];
>
> Is there an alternate approach that is superior? Or a way to convert a
> singleton relation back into a scalar that I am not aware of?
>
There was an "unbox" notation at one point for exactly this, but I'm not
sure it's still there.

I think it used a python *val notation.

The end result is a cross product anyway.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria/issues/732>.
>


-- 
Bill Howe
Associate Director and Senior Data Science Fellow, UW eScience Institute
Affiliate Faculty, Computer Science & Engineering
University of Washington
To acknowledge eScience: "Supported in part by the University of Washington
eScience Institute"

**Comment by BrandonHaynes** [comment]
Great, I'll see if I can dig up the unboxing syntax.
