### ISSUE TITLE
Add option to deployment configuration preventing accidental execution of setup_cluster.py

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria#742]
It probably isn't wise to hope that someone won't accidentally execute `setup_cluster.py` on the production server and destroy the catalogs.  We could add an option (`prevent_overwrite` or something) to the deployment configuration to prevent this; if someone really wanted to do it, they would then have to first modify the configuration and then execute the script.

**Comment by domoritz** [comment]
Dan was keeping backups of the catalog somewhere but I'm not sure who's responsible for that now.

**Comment by jingjingwang** [comment]
Yes, Dan was keeping backups for master catalogs. but here the problem happened on worker catalogs.

**Comment by senderista** [comment]
Weren't the backups just created manually before overwriting them? I don't
think it would be too hard to have a cron on master/workers take a backup
of the catalog every N hours/days and upload to S3...

**Comment by BrandonHaynes** [comment]
Taking a backup of any existing catalogs when running setup_cluster.sh is probably a smart idea too.
