### ISSUE TITLE
Remove worker catalog, move runtime confs to a text conf file

### ISSUE THREAD

**Issue by jingjingwang** [uwescience/myria#748]
Based on the discussion on Friday, I went through the current worker catalogs and yes I think we can get rid of them. We will put runtime configurations in a text conf file, and sync this text file when deploying/launching workers. That will help us with the upgrade problem.

**Comment by jingjingwang** [comment]
Related to https://github.com/uwescience/myria/issues/741

**Comment by senderista** [comment]
Fixed in #752
