### ISSUE TITLE
Deployment scripts need to copy keystore file to master root directory

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#756]
The Java keystore file for the prod cluster, `rest.myria.cs.washington.edu.jks`, is not copied to the `myria-production/master` directory by the `setup-cluster` deployment script, and hence `launch-cluster` always fails if SSL is enabled, until the keystore file is manually copied to that directory and `launch-cluster` is run again. Even just excluding the JKS file from deletion by `setup-cluster` (like the master catalog file) would be better than the current behavior.

**Comment by jingjingwang** [comment]
Looks like it's been fixed in d7976a99 (excluding from deletion). Do you think we need to add the auto copy part?

**Comment by senderista** [comment]
We have no future plans to support SSL termination in the MyriaX REST server (in EC2 deployments SSL should be offloaded to an ELB), so this fix is good enough.
