### ISSUE TITLE
Partitioning information is not stored in the catalog

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#766]
I ingested two new relations `armbrustlab:seaflow:opp_all` and `armbrustlab:seaflow:vct_all` (with hash partitioning attributes specified), and neither has partitioning information in the catalog:
```
sqlite> select how_partitioned from stored_relations where relation_name='opp_all';
{"pf":null,"workers":null}
sqlite> select how_partitioned from stored_relations where relation_name='vct_all';
{"pf":null,"workers":null}
```
The original ingest queries are here:
https://rest.myria.cs.washington.edu:1776/query/query-77550
https://rest.myria.cs.washington.edu:1776/query/query-77552

**Comment by jingjingwang** [comment]
This is not a bug, since the dataset was ingested by a JSON query not by a JSON "ingest". The feature of detecting the PF before a ``Store`` in a JSON query has not been implemented. I updated an example to show how to specify a PF in a JSON ingest in https://github.com/uwescience/myria/pull/767.

**Comment by senderista** [comment]
When https://github.com/uwescience/raco/issues/465 and https://github.com/uwescience/raco/issues/466 are complete, we can implement this missing feature (add a howPartitioned field to DbInsert, which will be populated by a new raco rule, and record it in the catalog when insert is complete).
