### ISSUE TITLE
Investigate more compact representation for hash aggregators

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#787]
In several aggregation operators (e.g., https://github.com/uwescience/myria/blob/8c1a0e74af25aaeb9f842da57515fafa8df4a914/src/edu/washington/escience/myria/operator/agg/MultiGroupByAggregate.java#L47), we have a `IntObjectHashMap<IntArrayList>` which maps hashes of a join or grouping key to indices of the corresponding tuples. For pure aggregators, we should expect there to be no duplicate tuples, so if we can ensure that there are no collisions between hash codes, then we do not need to incur the overhead of an `IntArrayList`; a single `int` value is all we need to store. To ensure that the probability of collisions is at most `1/N` (where we hash at most `N` items), we need to hash into a space of size ~ `N^2`. Therefore, to bound the collision probability at `2^-64`, we need `log((2^64)^2)` = 128 bits in the hash output. It would be convenient to use only 64-bit hashes, since that would let us use optimized primitive collections, but that would restrict us to only a few billion (`2^32`) keys before we expected collisions. If we can establish via profiling that this is a worthwhile optimization, then it might be worth writing our own optimized map for 128-bit keys (hopefully just by hacking a bit on the existing GS primitive collections).

**Comment by senderista** [comment]
I think we could get away with 64-bit hashes if we just maintain a counter for the input and abort if we've seen more than `2^32` tuples (technically we could track approximate distinct counts but I think that's too much complexity).

**Comment by jingjingwang** [comment]
Actually I have seen hash key collisions even only with several hundred of tuple batches. I can generate such an example later, but theory is just theory and we always need a backup plan. What if it happens? Do we kill the query and restart with standard hash tables? How do we know if it happened or not?

**Comment by senderista** [comment]
We can't know if it happened without doing key comparisons, of course. The reason you're seeing hash collisions is that they're expected: we're only keeping 4 bytes of a 128-bit hash (http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/hash/HashCode.html#asInt()), so we expect to see collisions after only 2^16 unique keys.

**Comment by jingjingwang** [comment]
I see, I didn't see this, thanks. Maybe... we can have two versions of hash tables (operators), one is safe and slow and one is assuming no collision, and making it as some configuration in RACO..?

**Comment by senderista** [comment]
For `DupElim`, we could just store the hash codes themselves without the indexes, since we don't need to look up an incoming tuple to determine if it's already present; we just look for the hash code and assume there are no collisions. (This is exactly how we would use a bloom filter, and in fact we could introduce a corresponding `ApproxDupElim` operator using a bloom filter.) Dan S. suggested we could call the hash-only version of `DupElim` "FAST DISTINCT" in MyriaL if we don't want to just replace the standard version.

**Comment by senderista** [comment]
For aggregates except `DISTINCT`, this is superseded by https://github.com/uwescience/myria/issues/876 (instead of assuming no collisions, we store collisions in an overflow table). We could still optimize `DupElim` as I described by storing only hash codes, but I think this can be closed for now.
