### ISSUE TITLE
Refactor `FileScan` operators

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#810]
The `FileScan` family of operators should be replaced by a single `DataInput` operator parametrized by a `DataSource` and `TupleReader` (new interface). The `TupleReader` implementations would contain the specialized logic for reading particular formats that currently resides in the various `FileScan` implementations. This would give us symmetry between the `import` and `export` implementations.

**Comment by jortiz16** [comment]
So far I've been able to refactor ``FileScan``` and ```BinaryFileScan``` without too many issues-- it seems like all the tests work ok. I wasn't sure about what to do for ```CatalogQueryScan``` and ```DbQueryScan```. These don't use an InputStream to read in tuples, but instead they use a tuple iterator. Is this going to be a problem? Would their DataSource be null?  (this doesn't seem right though) Can we build a stream based on an iterator? (is that even possible?)

**Comment by senderista** [comment]
I think we already discussed similar issues re: reading tuples from Postgres. My take is that the pattern of `DataSource` + `TupleReader` only makes sense for a byte stream + binary format, so I would advocate basically leaving these operators alone (they should implement the `DataInput` interface, whatever we decide to call it, but wouldn't compose other interfaces like `DataSource` and `TupleReader`).

**Comment by jortiz16** [comment]
I agree, but I have ```DataInput``` as an operator and not an interface. Should these other scans be implementing some sort interface? I must have missed that part.

**Comment by senderista** [comment]
No, I don't think you missed anything. I didn't really anticipate this issue. Let's discuss before/after 591d tomorrow?

**Comment by jortiz16** [comment]
Sounds great. Thanks!

**Comment by senderista** [comment]
@jortiz16 What's the status of this issue? Didn't you have a separate branch for this work?

**Comment by jortiz16** [comment]
This was merged in #824, but it was put on hold because it needs to be supported on the Raco side

**Comment by senderista** [comment]
Thanks for refreshing my memory :) I'll work on the Raco issue today.

**Comment by senderista** [comment]
fixed in 2e8ef86
