### ISSUE TITLE
Implement `DbQueryExecute` operator

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#816]
We need a generic operator for passing SQL to Postgres as-is. We can initially restrict MyriaL access to this operator to just creating views and indexes, but it would be useful to have the capability to execute arbitrary SQL on a given list of workers for user-generated query plans.

For particular applications like `CREATE VIEW` and `CREATE INDEX`, we can track the in-progress status of the created entities in the catalog and guarantee idempotence (and atomicity WRT visibility from the catalog APIs). For executing generic DDL, we need to use some distributed transaction facility like `PREPARE TRANSACTION` (http://www.postgresql.org/docs/9.4/static/sql-prepare-transaction.html). The coordinator will need to provide these distributed guarantees (possibly in a REST API implementation).

**Comment by jortiz16** [comment]
@senderista what do you mean by keeping progress of the entities through the catalog? Do you mean adding an extra column to the relations table (sort of like what we did for the delete feature)?

I need this feature for the PSLA integration with Myria. I could help implement implement the DbExecuteOperator for at least the ```create view``` and ```create index``` cases. How does that sound?

**Comment by senderista** [comment]
Yes, I believe I meant recording the status of the operation on each partition. Idempotent retry of a "create view/index" operation would just create the view/index/whatever on each partition where it doesn't exist (similar to the delete operation).

What do you need exactly for the PSLA integration? Do you just need views/indexes? I'd rather avoid implementing a generic passthrough operator if we don't need it (since it would require distributed transactions).

**Comment by jortiz16** [comment]
Yes, I need it in order to create views. I mean, I could do it the old-fashioned way -- (creating .sql scripts, broadcasting to all the workers, and then running each script locally). Since both ```create index``` and ```create views``` is idempotent, I don't see harm in supporting just these two operators. 

I don't need the "generic" (run anything on postgres) operation. This is not only more complicated but can be harmful too. Someone could run "DROP tables" or really mess up the state of the underlying database.

**Comment by senderista** [comment]
OK, so you would implement a new operator for each of `CREATE VIEW` and `CREATE INDEX`? That should be fine. Looks like there's already index support in `edu.washington.escience.myria.accessmethod.JdbcAccessMethod`. Can you just use that? Could you add view support to the same class (with Postgres-specific extensions being delegated to helper methods)? Also, do you need materialized views?

**Comment by BrandonHaynes** [comment]
This would be handy for me as well, where I just needed to manually create UDFs on every worker in Postgres.  Other than the security risk associated with table dropping, is there a reason not to just send an arbitrary string to the configured back-end, and allow it to execute it in whatever way makes sense?

**Comment by jortiz16** [comment]
This is a stretch but a user could potentially change the schema of underlying tables or change the state of the tables in such a way that the Myria catalog would be out-of-sync. So maybe this shouldn't be a feature exposed to the users via MyriaL/Raco.....

Or we could do both....
 1) create view and index operators and expose this feature to users in the future
 2) create a DBQueryExecute operator for us (we know the risks)

**Comment by senderista** [comment]
Right, I can see at least two major risks of allowing arbitrary DDL in a passthrough operator:

* It could invalidate the Myria catalog
* It will in general not be idempotent, so retries could have unexpected side effects

It may be enough if we just document that any DDL must be idempotent and not invalidate catalog metadata, and let the user assume the risks above. In that case, we can relax the requirement of transactional consistency and just track the status of the operation on each partition, with users required to retry the operation manually if the query does not return success. (Note that tracking operation status per-partition is just an optimization; we still need idempotence since the operation could have succeeded locally but the coordinator may not have persisted that status in the partition's catalog entry.)

Right now it seems like a big win to let users execute arbitrary SQL locally. It would unblock several scenarios without requiring us to do specific work to enable them (even if we should eventually). I do think `CREATE VIEW` and `CREATE INDEX` operators are important enough that we should implement them sooner rather than later (and as I noted,` CREATE INDEX` seems to already be supported in `JdbcAccessMethod`).

**Comment by jortiz16** [comment]
Thanks for the heads up on the ```JdbcAccessMethod``` calls. For now, if we create these view and index operators, should we expose them through a REST API? (like we did for DbDelete?) 

Also, as we create these views and we add them to the Relation table in the catalog, these relations would have a value of ```1```  for a new column labeled ```isView```.  Then, if someone runs a delete operation on a view, we could change the command to ```DROP VIEW ... ``` instead of ```DROP TABLE...```. Other operations should not be supported such as creating an index on a view. 

Or to make our lives easier, we can just add the view to the master catalog, but not support any other operations. 

By the way, I'm only implementing support for views, not materialized views.

How does this sound? We can also discuss this more tomorrow.

**Comment by senderista** [comment]
From today's meeting with @mbalazin, @jingjingwang, @parmitam:

There are two possible extremes here: directly support everything in MyriaL (e.g., have native Myria views), or just pass arbitrary SQL through to Postgres. A middle ground would be to have specific syntax for defining views/indexes/UDFs in Postgres, but add metadata to the Myria catalog and handle idempotence ourselves in a SQL wrapper (on retry, we should just overwrite any objects with the same name that are already present on a worker). As with DELETE, we just make all local operations idempotent and expect the user to retry on query failure. We would defer all syntax checking/other validation to Postgres (Myria catalog metadata would just be overwritten if present). It's possible that our "wrapper SQL" (which handles idempotence) would be backend-specific, but hopefully not. Users will have to be aware, however, that the DDL they specify may only be valid for a particular backend.

**Comment by jortiz16** [comment]
What sort of catalog metadata would we be keeping track of for UDFs? 

For example, for indexes, this is something we can track of in the catalog under the ```relation_schema``` relation. For views, we can probably do what I was suggesting above by marking relations as ```is_view```. 

For UDFs, I am not sure what we want to keep track of?

**Comment by senderista** [comment]
Fixed in #830.
