### ISSUE TITLE
OutOfMemory does not lead to query failure immediately

### ISSUE THREAD

**Issue by jingjingwang** [uwescience/myria#817]
I have observed such a case where I saw OutOfMemory in worker's stderr, but the query was still running for an infinite amount of time until I had to kill it. It happens sometimes when the heap size limit is close to the working set size. We need to investigate it more. 
I remember that we observed similar cases before -- having a query running forever. It may explain them.

**Comment by senderista** [comment]
Is this on the `reef` branch?

**Comment by senderista** [comment]
To elaborate, on the `reef` branch, if a worker exceeds allocated memory, then the YARN NodeManager will kill it. Or, if the machine is low on memory, then the Linux OOM killer might terminate it. Either way, the `Driver` will time out on heartbeats from that worker and declare the `Evaluator` dead, which will fire a `LostHeartbeatException` from the coordinator, which should always fail the query.

**Comment by jingjingwang** [comment]
No it's the main branch. I'll look at it more deeply.

**Comment by jingjingwang** [comment]
The PR is merged and I believe this issue is resolved.
