### ISSUE TITLE
Renaming Import From Database

### ISSUE THREAD

**Issue by jortiz16** [uwescience/myria#820]
Currently, we have two definitions for "import" in Myria: 

1. ingesting data from a data source
2. updating the catalog with existing relations in Postgres

@mbalazin suggested we rename 2. to "updateCatalog". Does anyone disagree or have a suggestion for a different name? (also tagging: @senderista , @jingjingwang )

**Comment by senderista** [comment]
I feel that "update" is unclear and doesn't convey the notion of the catalog "assuming ownership" of a distributed relation in Postgres, but I haven't been able to think of an alternative I really like. Something like `attachDataset` or `adoptDataset` is what I'm getting at, but I don't particularly like either.

**Comment by jortiz16** [comment]
I agree about "update" being vague. What about ```addDatasetToCatalog``` or ```addExistingDatasetToCatalog```. They are long but they literally say what the system is doing.

**Comment by senderista** [comment]
I agree that verbose names are clearer. I think `addDatasetToCatalog` is sufficiently clear.

**Comment by BrandonHaynes** [comment]
Random idea: unify the two types of import by introducing a `PostgresSource` data source which supports both the in-place (i.e., just adding an existing relation to the catalog) and copy (make a complete copy of a potentially-foreign Postgres table) options.

**Comment by jortiz16** [comment]
I like that idea of unifying both types. Currently, in-place imports are similar to an ingest call but only makes sure to use flag the ```overwriteTable``` boolean to false (inside a DbInsert operator). 

If we create a ```PostgresSource``, we are required to return an InputStream... if it's empty, would this would create a problem for a FileScan operator that is reading from this source? I'm not sure myself,  I would need to take a closer look.

Also, I haven't heard of people making a copy from a foreign Postgres table yet.... Is that something others are doing? I'm assuming it means having one worker read data from another worker?  Or would this worker be reading from another machine that is not in the Myria cluster?

**Comment by BrandonHaynes** [comment]
Seems reasonable to just return the underlying tuples in a (hypothetical) `PostgressSource` operator.  Can always sink them if our only goal is to add to the catalog.  I guess that could be a separate flag (e.g. `silent=true`), as well.

An copy-in-place Postgres import query would look something like below.  It's a shame we'd have to explicitly do something with the result -- maybe we should drop the `inplace` flag and have users explicitly store the result?

```python
R = import('public:adhoc:foo', postgres(inplace=true);
sink(R);
```

**Comment by senderista** [comment]
I think this would be conceptually cleaner if we first refactor per https://github.com/uwescience/myria/issues/810. Then we'd have a single `DataInput` operator implementation parametrized by a `TupleReader` and `DataSource`. That said, the `DataSource` abstraction doesn't really fit the Postgres import semantics very well; it always represents an opaque byte stream which is parsed by the (hypothetical) `TupleReader` implementation. Perhaps the Postgres import semantics would be better expressed by a `TupleSource` whose generic implementation would be parametrized by a `DataSource` and `TupleReader`, but in the Postgres import case would have a different implementation parametrized only by the relation name. @jortiz16 and @BrandonHaynes, what do you think?

**Comment by jortiz16** [comment]
I don't quite understand the second suggestion: "_be better expressed by a TupleSource whose generic implementation would be parametrized by a DataSource and TupleReader_". Can you give an example?

If we stick with a DataInput operator parameterized by a ```TupleReader``` and ```DataSource``` option (the first suggestion), we can use what @BrandonHaynes suggested: if it's an import, we can simply return an empty InputStream ( sort of what ```EmptySource.java``` does right now) based on a flag option. The ```TupleReader``` would then not have anything to parse, but that should be ok.

About merging with #810, I agree that symmetry would be nice. It might be a bit tricky for some of the scans. For example, the TipsyFileScan operator uses two input streams. I guess this might just require it's own special DataSource to handle this, right?

If if we combined this issue with #810, these are the steps: 

1) Create the DataInput operator
2) Add a PostgresSource implementation (with a flag option). 
3) Create the TupleReader interface
4) Convert Scan operators to classes that implement TupleReader: TipsyReader, NChiladaReader, CatalogReader, QueryReader, SeaflowReader, BinaryReader, FileReader (some of these might need their own specialized DataSource as mentioned above)
5) Replace the importFromDatabase method in Server.java to use the DataInput/PostgresSource options

How does that sound?

**Comment by senderista** [comment]
I think that `TupleReader`s that require extra metadata (like the Tipsy implementation) should specify an extra `DataSource` for each metadata source. That removes all magic from the Myria layer and keeps it in Raco (where I think it belongs). I don't think we should try to extend `DataSource` with extra input streams etc., since it simply represents an addressable opaque byte stream.

Re: the `DataInput` operator with a local Postgres source: I think this case can be covered by a  `TupleReader` implementation that takes a relation name in its constructor, ignores the `InputStream` argument to `TupleReader.setInputStream()`, and returns tuples directly from JDBC (so `DataInput` might be initialized with something like [`NullInputStream`](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/NullInputStream.html)). I think it's more natural to put the Postgres-specific logic in `TupleReader` than `DataSource`; do you disagree?

**Comment by senderista** [comment]
Sorry, what I really meant to say above was that in the case of a Postgres import, `DataInput` should be parametrized with `EmptySource` (and `PostgresReader`). Forget what I said about `NullInputStream`. Again, that will happen automatically in Raco when the serialized query plan is constructed.

**Comment by senderista** [comment]
We are tracking the Tipsy/Nchilada parallel ingest support in Raco in https://github.com/uwescience/raco/issues/158. This issue is fixed in https://github.com/uwescience/myria/pull/821.
