### ISSUE TITLE
Platform independent code formatter

### ISSUE THREAD

**Issue by jingjingwang** [uwescience/myria#828]
Our current code format is controlled by Eclipse according to org.eclipse.jdt.core.prefs. This approach is both platform and version dependent, so that any upgrade to Eclipse may lead to a huge number of diffs. Switching to an independent one seems to be a better idea, while people who are not using Eclipse can live with the same set of rules.

We can discuss which formatter to use. I also hope that we can make formatting as one part of travis checks, although I'm not sure if it's reasonable.

**Comment by jingjingwang** [comment]
This seems to be a reasonable one: https://github.com/google/google-java-format

**Comment by senderista** [comment]
fixed in #829
