### ISSUE TITLE
Error in connecting to EC2 server from Notebook

### ISSUE THREAD

**Issue by myeong** [uwescience/myria#836]
Hi, 

I installed Myria on EC2 and using Jupyter Notebook.
I tried to run this code: 

```

from myria import *

connection = MyriaConnection(rest_url='http://ec2-54-187-60-23.us-west-2.compute.amazonaws.com:8753')

query = MyriaQuery.submit(
"""calls = load('https://s3-us-west-2.amazonaws.com/census-cdr/test/MItoMI-2013-11-01.txt',
                csv(schema(time:int, source:int, dest:int, call:float), skip=0, delimiter="\t"));   
   store(calls, cdr);""", connection=connection)

df = query.to_dataframe()
df.head()
```

and I got this error
`ConnectionError: HTTPConnectionPool(host='ec2-54-187-60-23.us-west-2.compute.amazonaws.com', port=80): Max retries exceeded with url: /execute (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f3f7d98fb90>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Any clue or suggestion? 
Thanks!

**Comment by BrandonHaynes** [comment]
Hi Myeong --

Since the Myria web interface isn't running on port 80, you'll need to explicitly specify the execution URL.  Try instantiating like this:

```python
connection = MyriaConnection(rest_url='http://ec2-54-187-60-23.us-west-2.compute.amazonaws.com:8753', execution_url='http://ec2-54-187-60-23.us-west-2.compute.amazonaws.com:8080')
```

We'll need to address this in our sample notebook.  Thanks for bringing it to our attention!

**Comment by myeong** [comment]
it works! thanks!
