### ISSUE TITLE
Postgres rejects gettingStarted query

### ISSUE THREAD

**Issue by dhutchis** [uwescience/myria#840]
Sometimes when running the curl query from the gettingStarted example `curl -i -XPOST localhost:8753/dataset -H "Content-type: application/json"  -d @./ingest_smallTable.json`, I get an exception
`SQLState: 23505, Msg: ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"`

Not sure how to reproduce it.  Sometimes the curl works for me, sometimes it doesn't.

`Detail: Key (typname, typnamespace)=(public:MyriaSysTemp:smallTable, 2200) already exists.`
But the table `public:adhoc:smallTable` does not exist.

**Comment by jortiz16** [comment]
Thanks! If anyone experiences this issue or something similar, please let us know so we can figure out how to reproduce it.

**Comment by jingjingwang** [comment]
Did this happen with `overwrite:false`? (The example has it to be `true`)

**Comment by dhutchis** [comment]
It happens with both overwrite:false and overwrite:true.

**Comment by dhutchis** [comment]
Found the cause!  The `persist_uri` parameter in deployment.cfg is not optional.  This error occurs when it is not set.  After setting it everything works.

**Comment by dhutchis** [comment]
Aiee, nevermind. The exception started popping up again, though it seems like it only pops up when overwrite is `true` now.

**Comment by BrandonHaynes** [comment]
Possibly related to concurrent query submission?  See https://www.postgresql.org/message-id/11235.1268149874@sss.pgh.pa.us

**Comment by dhutchis** [comment]
You may be on the spot Brandon.  If the issue were related to workers
trying to create a table in Postgres at the same time, then it would
explain how sometimes the error appears and sometimes the query goes
through, because it is a timing bug.  I'm not sure what to do to help
further, but I can reliably reproduce the error on my Myria right now.

**Comment by dhutchis** [comment]
@jortiz16 solved the issue.  I was sharing Postgres databases between the workers on the same node.  Everything works if we allocate a separate Postgres database to each worker.
