### ISSUE TITLE
Add new version of `MultiGroupByAggregate` that uses bulk `Aggregator.add()` interface

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#855]
For new `Aggregator`s which reside out-of-process (like Python UDAs), the approach taken in `MultiGroupByAggregate` of calling `Aggregator.addRow()` on each input row, with the state passed back and forth for each call (since `Aggregator`s are stateless) is not scalable due to messaging overhead. We need to revise the implementation to call `Aggregator.add()` instead (presumably the `TupleBatch` argument would either be all input tuples augmented with grouping keys, or all input tuples associated with a particular grouping key).

**Comment by parmitam** [comment]
fixed with blob, and python udf support
