### ISSUE TITLE
MasterCatalog needs to store UDF arity and output type

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria#861]
It looks like the `MasterCatalog` is only storing UDF names, but not arity or return type.  While this probably worked okay when the functions were fixed to be binary (and required to return an integer), these data will need to be stored in order to correctly compile RACO expressions.  The details will also need to be surfaced in the `/functions` API endpoint.

**Comment by BrandonHaynes** [comment]
Also need language, and source (when available).  JSON should look like this:

```
[["udf1", STRING_TYPE, "Python", "def foo(x): pass"], ...]
```

**Comment by parmitam** [comment]
master catalog stores output type now.  Arity support is provided by multi-valued flag.
