### ISSUE TITLE
Use `TupleBatchBuffer` in `TupleBatch` builders

### ISSUE THREAD

**Issue by parmitam** [uwescience/myria#865]
some of the tuple batch building functions need to be cleaned up to use TupleBatchBuffer, instead of an explicit list of ColumnBuilders, in order to build a TupleBatch. ColumnBuilders should just be internal data structures of a TupleBatchBuffer most of the time, and their sizes are determined by the TupleBatchBuffer.

**Comment by senderista** [comment]
@parmitam @jingjingwang what's the status of this issue?
