### ISSUE TITLE
SingleColumnAggregatorFactory.aggOps does not need to be an array

### ISSUE THREAD

**Issue by jingjingwang** [uwescience/myria#871]
For historical reasons (..?),  the state of a single column aggregate contains many fields such as: count, int, sum, etc, and we expect expressions such as `sum(column), count(column)` to be compiled to only one `SingleColumnFactory` with two `aggOps`: `sum` and `count`. However, `aggOps` is only set to be a single element array in RACO (https://github.com/uwescience/raco/blob/master/raco/backends/myria/myria.py#L488), and is a waste of memory when not [all the states](https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/operator/agg/IntegerAggregator.java#L155) are used. Even if all the states are used, I don't see memory saving in this design either. We can make each agg state as a column in a `MutableTupleBuffer` which uses the same amount of memory as a primitive field in `IntAggState`.

I'd like to change [this](https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/operator/agg/MultiGroupByAggregate.java#L45) to something similar as the hash tables in `SymmetricHashJoin`, and maybe wrap up the whole hash table logic into some class for both operators if possible. This should help with memory usage and also provide a clear abstraction.

**Comment by jingjingwang** [comment]
I'd like to hear your thoughts on it @senderista @parmitam . Is there any important thing missing?

**Comment by senderista** [comment]
Totally agree with this design. It would be even better if we combined it with https://github.com/uwescience/myria/issues/787 ;-)

**Comment by senderista** [comment]
fixed in #874
